name: Build SO

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26b
          local-cache: true

      - name: Build with NDK
        run: |
          $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++ -shared -fPIC main.cpp -o libxenocheat.so -llog

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: libxenocheat
          path: libxenocheat.so
          
